---
- hosts: vms
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"

  tasks:
    - name: Create VMs without a data drive
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ inventory_hostname }}"
        template: "{{ vm_template }}"
        state: poweredon
        disk:
          - size_gb:  "{{ disk1_size }}"
            type: thin
            datastore: "{{ datastores | random }}"
        hardware:
          memory_mb: "{{ ram }}"
          num_cpus: "{{ cpus }}"
      when: disk2_size is undefined

    - name: Create VMs with a data drive
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ inventory_hostname }}"
        template: "{{ vm_template }}"
        state: poweredon
        disk:
          - size_gb:  "{{ disk1_size }}"
            type: thin
            datastore: "{{ datastore }}"
          - size_gb:   "{{ disk2_size }}" 
            type: thin
            datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ ram }}"
          num_cpus: "{{ cpus }}"
      vars:
          datastore: "{{ datastores | random }}"
      when: disk2_size is defined

    - name: Wait for VMs to boot up
      pause:
        minutes: 3
